#!/usr/bin/env bash

main() {

if ! [ -x "$(command -v subl)" -a -x "$(command -v slack)" -a -x "$(command -v code)" -a -x "$(command -v spotify)" ]; then
 	echo 'Error: Sublime/Slack/Spotify/Code is not installed.' >&2
 	exit 1
fi

sleep 1
i3-msg focus down
i3-msg workspace "3"
firefox &
sleep 5

i3-msg focus down
i3-msg workspace "4"
sleep 1
slack &
sleep 5

i3-msg focus down
i3-msg workspace "5"
spotify --force-device-scale-factor=3 & 
sleep 5

i3-msg focus up
sleep 0.5
i3-msg workspace "9"
code &
sleep 5
i3-msg focus down

exit 0
}

main 1> /dev/null 2> /dev/null
